#!/bin/bash
LIST_DISPLAY_LINE_NUM=6
LIST_DISPLAY_MARKER='\033[;32m*\033[0m'

type_list=\
"feat,A new feature#\
fix,A bug fix#\
docs,Documentation only changes#\
style,Changes that do not affect the meaning of the code #\
refactor,A code change that neither fixes a bug nor adds a feature#\
perf,A code change that improves performance#\
test,Adding missing or correcting existing tests#\
chore,Changes to the build process or auxiliary tools and libraries such as documentation generation#"

# Display 4 line type description, start by specified $1, and put a marker at 
# $2
# 
# LIST_TITLE:
#	hint show at the top of list
# LIST_ADAPTER: 
#	Which list(array) you want to display. With two clonm, one is
# 	item name, and two is description(or null), seperating by ',"
# LIST_COUNT
#	Count of list item
# LIST_INDEX_START:
#	Start item
# LIST_INDEX_SELECTED:
#	Selected item
# LIST_DISPLAY_DIR
#	If defined as "back", go back to the line where list display
# LIST_DISPLAY_LINE_NUM:
#	Number of list to display
# LIST_DISPLAY_MARKER:
#	A charater, mark at the beginning of selected line
list_display()
{
	# move cusor to start
	echo -ne "\r"

	# no wrap
	echo -ne "\033[?7l"

	# hide cusor
	echo -ne "\033[?25l"

	# print type and description start by $1
	line=$LIST_INDEX_START
	line_max=$[$LIST_INDEX_START + $LIST_DISPLAY_LINE_NUM]
	blank_line_max=$line_max

	if [ $line_max -gt ${#LIST_ADAPTER[@]} ]; then
		line_max=${#LIST_ADAPTER[@]}
	fi

	# put item to console
	while [ $line -lt $line_max ]
	do
		IFS=','
		item=(${LIST_ADAPTER[$line]})

		if [ $LIST_INDEX_SELECTED -eq $line ]; then
			marker=$LIST_DISPLAY_MARKER
		else
			marker=" "
		fi

		echo  -e "$marker [${item[0]}] ${item[1]} \E[K"
		line=$[ $line + 1 ]
	done

	# put blank line
	while [ $line -lt $blank_line_max ]
	do
		echo
		line=$[ $line + 1 ]
	done
	
	# show cusor
	#echo -ne "\033[?25h"

	# Go back to fist line
	if [ "$LIST_DISPLAY_DIR" = "back" ]; then
		echo -ne "\E[$[${LIST_DISPLAY_LINE_NUM}]A"
	fi

}

list_display_clear()
{
	line=0
	echo -ne "\r"
	while [ $line -lt $LIST_DISPLAY_LINE_NUM ]
	do
		echo -e "\E[K"
		line=$[ $line + 1 ]
	done

	# Go back to fist line
	if [ "$LIST_DISPLAY_DIR" = "back" ]; then
		echo -ne "\E[$[${LIST_DISPLAY_LINE_NUM}]A"
	fi
}

list_select_up()
{
	if [ $LIST_INDEX_SELECTED -gt 0 ]; then
		LIST_INDEX_SELECTED=$[ $LIST_INDEX_SELECTED - 1 ]
	fi

	if [ $LIST_INDEX_SELECTED -lt $LIST_INDEX_START ];then
		LIST_INDEX_START=$[ $LIST_INDEX_START - 1]
	fi

}

list_select_down()
{
	index_max=$[ $LIST_COUNTS - 1 ]
	if [ $LIST_INDEX_SELECTED -lt  $index_max ]; then
		LIST_INDEX_SELECTED=$[ $LIST_INDEX_SELECTED + 1 ]
	fi
	
	if [ $[ $LIST_INDEX_SELECTED - $LIST_INDEX_START ] \
		-ge $LIST_DISPLAY_LINE_NUM ]; then
		LIST_INDEX_START=$[ $LIST_INDEX_START + 1 ]
	fi
}

list_open()
{
	# move cusor to start
	echo -ne "\033[?18l"

	LIST_INDEX_START=0
	LIST_INDEX_SELECTED=0
	LIST_COUNTS=${#LIST_ADAPTER[@]}
	LIST_DISPLAY_DIR="back"
	echo -e $LIST_TITLE
	list_display
	while [ : ]
	do
		read -s -N1
		case $REPLY in
			j)
				list_select_down
				;;
			k)
				list_select_up
				;;
			\n)
				break;
				;;
			q)	
				break;
				;;
		esac
		list_display
	done
	list_display_clear

}

# return to home position
home()
{
	echo -ne "\E8"

}

begin()
{
	# clear screan, got to console home position, and save this position.
	echo -ne "\E[H\E[2J\E7"
}

end()
{
	echo [finish...]
}

main()
{
	begin

	IFS="#"
	LIST_ADAPTER=($type_list)
	LIST_TITLE="Chose a type:"
	list_open

}

main
